name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pandoc
        run: apt install pandoc

      - name: Compile rules
        run: pandoc -s -f markdown -t html rules.md -o index.html
